# shared_exception_handling